  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Information"
  weight = 200
  identifier = "information"
  url = "/post/information/"

  [[main]]
  name = "Reviews"
  weight = 200
  identifier = "reviews"
  url = "/post/reviews/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"
